version: "3.9"
services:
  bot:
    image: node:18-alpine
    restart: always
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && npm run start"
    env_file:
      - .env
    ports:
      - "127.0.0.1:${PORT}:${PORT}"
